### PR TITLE
Add support for codec switching using SourceBuffer.changeType()

### PR DESCRIPTION
**Pull request by wolenetz**
* Includes codec-switching mention in title and abstract.
* Adds changeType() method and algorithm.
* Updates segment parser loop to disallow a media segment immediately
  following changeType() (without intervening initialization segment).
* Updates initialization segment received algorithm to allow for codec
  changes.
* Updates Byte Stream Formats section's text around codec changes.
* Updates media-source.js to include linkages for new definitions.
* Includes a regenerated index.html.

### CODE REVIEW

**Comment by wolenetz** [comment]
@jyavenard - please take a look. I believe this contains the logic we agreed upon during our recent face-to-face.

Note specifically the steps in the new changeType() method do not explicitly check if the parent MediaSource is 'closed'. However, the check to see if the SourceBuffer is still in that parent MediaSource's sourceBuffers attribute is sufficient for that.

Also, it's allowed for changeType() to occur when !updating, but PARSING_MEDIA_SEGMENT. There is a step included to reset the parser state which handles that. There is also a new flag that tracks whether or not an init segment is still needed following a recent changeType() call.

Finally, changeType() conditionally sets the mode to 'sequence' if the corresponding generate timestamps flag is true. Note that it leaves the mode as-is if that generate timestamps flag for the new type is false (preserving, for example, whatever mode the app had previously been using, in that case).

I'd like to merge this ASAP to the wicg/media-source repo's codec-switching branch.

Here's a hopefully helpful htmldiff of the newly generated spec html containing the delta in this PR (which also includes respec updates since the last w3c/media-source editor's draft from over a year ago):
https://services.w3.org/htmldiff?doc1=https%3A%2F%2Frawgit.com%2Fwicg%2Fmedia-source%2Fcodec-switching%2Findex.html&doc2=https%3A%2F%2Frawgit.com%2Fwolenetz%2Fmedia-source%2Fcodec-switching-spec%2Findex.html

**Comment by jyavenard** [comment]
Looks good, some questions:

In  Initialization Segment Received 
step 3: "If the first initialization segment received flag is true, then run the following steps: "
the step "The codecs for each track, match what was specified in the first initialization segment . " was removed.

However, there's no dependency for this condition on the value of "pending initialization segment for changeType flag".
The consequence of this removal is that a new init segment that use a new codec, is now accepted so long as the number and type of tracks are the same.
Same in "10. Byte Stream Formats"

Is this what we really want? It makes the need for changeType method unnecessary so long as the container stays the same.
Shouldn't we enforce the use for changeType() before changing the codec too? (I had a different opinion a few months ago, but I've now revisited it)

On triple thought, that you can change codec on the fly easily will be appreciated.

So all look good to me.

**Comment by wolenetz** [comment]
@jyavenard Yes, I went with what I understood to be the result of our previous discussions (with which I agree). To help encourage better web app behavior (e.g. don't fetch and append until you're confident in user agent support), and with the allowances for user agents to determine whether or not the codec change is supported, I'll also add the following to the two updated non-normative notes:

* following "...Implementations are encouraged to trigger error in such cases only when the codec is indeed not supported or the other two properties' checks fail." I'll add: "Web authors are encouraged to use changeType(), addSourceBuffer(), and isTypeSupported() with precise codec parameters to detect user agent support. changeType() is required if the bytestream format is changing."

* following "...Implementations are encouraged to trigger error in such cases only when the codec is indeed not supported." I'll add the same as above.

[edit: I included "precise codec parameters to **more proactively** detect" in 29ede6c.]

**Comment by wolenetz** [comment]
Thanks for the discussions and review, @jyavenard 
I'll proceed now to implement this in Chrome behind an experimental flag (and add appropriate web-platform-tests). Please report if there are further changes to this incubation spec needed (probably best as a comment on the w3c issue for this feature: https://github.com/w3c/media-source/issues/155).

**Pull request merged**
